# Core imports
import json
import math
from pprint import pprint as pp

# Library imports
import networkx as nx
from networkx.readwrite import json_graph
import matplotlib.pyplot as plt
from tqdm import tqdm, trange
import fire

# Constants
DATASET_SIZE = 4_107_340
CONFERENCE_IDS = ['1184914352', '1127325140', '1203999783']
CONFERENCE_NAME = 'AAAI-NIPS-IJCAI'
AUTHOR_IDS = [('563069026', 'Hinton'), ('161269817', 'Bengio'),
              ('2053214915', 'LeCun')]
# CONFERENCE_IDS = ['1130177464', '1190910084', '1140684652']
# CONFERENCE_NAME = 'SODA-STOC-SIGIR'
# AUTHOR_IDS = [('2171343426', 'Pnueli')]
AUTHOR_COLOR = "#eb3dce"
PAPER_COLOR = "#57def2"
COLOR_PALETTE = [
    ('#FECEE9', '#EFA0CD', '#FF66BC', '#4F032E', "#0F0008"),
    ('#D4E4BC', '#AAB796', '#6B8E36', '#576D36', '#384722'),
    ('#BAD3E0', '#5FA7CE', '#2DB5FF', '#0091E0', '#275B77'),
    ('#F9EDEE', '#DBA6AB', '#E63946', '#9E454C', '#561C21'),
]
TURING_AWARD_YEAR = 2018
DATASET_BASE_PATH = './dblp_arnet/'


def get_data(dictionary):
    '''
        Given a dictionary, parse the necessary data contained in it
    '''
    return {
        'id': dictionary.get('id', 0),
        'title': dictionary.get('title', ''),
        'year': int(dictionary.get('year', 0)),
        'authors': dictionary.get('authors', []),
        'references': dictionary.get('references', []),
    }


def generate_graph(save_records: bool = False,
                   save_gml: bool = False,
                   save_yearly_gml: bool = False,
                   plot_graph_figure: bool = False,
                   read_from_dblp: bool = False,
                   generate_graph: bool = False,
                   figure_save_path: str = "graph.svg",
                   plot_save_path: str = 'plot.png',
                   graph_file: str = 'graph.gml',
                   dblp_filename: str = 'dblp_papers_v11.txt'):
    '''
        ## Parameters

        `save_records`: Save the records fetched to a file

        `save_gml`: Save the final graph generated to a GML file,
                    named by `graph_file`, prepended with the year

        `save_yearly_gml`: Save the graph generated in each year timestep to a
                           GML file

        `plot_graph_figure`: Tries to apply a spring layout to the graph and
                             print it. Use it carefully

        `read_from_dblp`: Read the graph from the dblp json file.
                          If false, reads the GML from `graph_file`

        `generate_graph`: If True, generates a graph from the conferences read
                          if `read_from_dblp` was True

        `figure_save_path`: Path to save the figure generated by calling this
                            with `plot_graph_figure`

        `plot_save_path`: File to plot the chart generated interactively
                          inside `save_yearly_gml`

        `graph_file`: GML filename which is read and/or saved the graph to
    '''

    G = nx.DiGraph()
    conference_papers = {}

    # Read file adding to array
    if read_from_dblp:
        with open('./dblp_arnet/{}'.format(dblp_filename), 'r') as f:
            for line in tqdm(f, total=DATASET_SIZE):
                parsed_json = json.loads(line)
                try:
                    if parsed_json['venue']['id'] in CONFERENCE_IDS:
                        # If doesn't have year in the dictionary
                        if parsed_json['year'] not in conference_papers:
                            conference_papers[parsed_json['year']] = []

                        conference_papers[parsed_json['year']].append(
                            get_data(parsed_json))
                except KeyError as e:
                    pass

    plt.ion()
    plt.figure(figsize=(30, 24))
    ax1 = plt.subplot(311)
    ax1.set_title('Degree (Citations)')
    ax2 = plt.subplot(312)
    ax2.set_title('PageRank')
    ax3 = plt.subplot(313)
    ax3.set_title('Closeness')
    old_plots = {name: {'year': [], 'dg': [], 'cn': [], 'pr': []}
                 for id, name in AUTHOR_IDS}
    older_papers = {}

    for year in range(1890, 2020):

        if generate_graph and read_from_dblp:
            print("Parsing year {}".format(str(year)))

            # Add papers and authors to be referenced later
            for paper in conference_papers.get(year, []):
                older_papers[paper['id']] = [
                    author for author in paper['authors']]

            for paper in conference_papers.get(year, []):
                # Adiciona/atualiza nodos dos autores
                for author in paper['authors']:
                    G.add_node(author['id'],
                               name=author.get('name', ''),
                               count=G.node[author['id']].get('count', 0) + 1 if author['id'] in G.nodes() else 1)  # nopep8

                # Adiciona arestas
                for citation_id in paper['references']:
                    if citation_id in older_papers:
                        # Other paper authors
                        for other_author in older_papers[citation_id]:
                            # This paper authors
                            for author in paper['authors']:
                                G.add_edge(author['id'], other_author['id'])

            print("Current Graph size: {} nodes and {} edges".format(
                G.number_of_nodes(), G.number_of_edges()))
        else:
            gml_filename = DATASET_BASE_PATH + \
                '{}_{}_{}'.format(CONFERENCE_NAME, year, graph_file)
            print("Reading graph from GML file {}".format(gml_filename))
            try:
                G = nx.read_gml(gml_filename)
                print("Finished reading graph from GML file")
            except FileNotFoundError:
                G = nx.DiGraph()
                print("Generating empty graph, as there is no file")

        if plot_graph_figure:
            # Draw graph
            f = plt.figure()
            plt.title("Authors references graph until {}".format(str(year)))
            node_sizes = [degree + 1 for node, degree in list(G.in_degree())]
            nx.draw_spring(G, node_size=node_sizes, alpha=0.4,
                           arrowsize=2, arrowstyle='- >')

            # Save graph
            f.savefig(str(year) + "_authors_" + figure_save_path)
            # plt.show()
            plt.close()
            print("Saved figure for year {}".format(str(year)))

        if save_yearly_gml and G.number_of_nodes() > 0:
            # Computing PageRank
            print('Generating PageRank to save year gml')
            pr = nx.pagerank(G)
            nx.set_node_attributes(G, pr, 'pagerank')

            # Counting node degrees
            print('Generating Degrees count to save year gml')
            # i_dg = {node: degree for node, degree in list(G.in_degree)}
            # nx.set_node_attributes(G, i_dg, 'indegree')
            # o_dg = {node: degree for node, degree in list(G.out_degree)}
            # nx.set_node_attributes(G, o_dg, 'outdegree')
            dg = dg = {node: degree for node, degree in list(G.degree)}
            nx.set_node_attributes(G, dg, 'degree')

            # Computing betweeness
            # print('Generating betweenness to save year gml')
            # bn = nx.betweenness_centrality(G, normalized=True)
            # nx.set_node_attributes(G, bn, 'betweenness')

            print('Generating closeness to save year gml')
            cn = nx.closeness_centrality(G)
            nx.set_node_attributes(G, cn, 'closeness')

            # Saving graph to .gml file
            gml_filename = DATASET_BASE_PATH + \
                '{}_{}_{}'.format(CONFERENCE_NAME, year, graph_file)
            nx.write_gml(G, gml_filename)
            print("Saved graph to .gml file")

            # Remove old lines from interactive plot
            for ax in [ax1, ax2, ax3]:
                for l in ax.get_lines():
                    l.remove()

            # Plot PR
            for author_idx, (author_id, author_name) in enumerate(AUTHOR_IDS):
                if author_id in dg:
                    # Append to data
                    old_plots[author_name]['year'].append(year)
                    # old_plots[author_name]['i_dg'].append(i_dg[author_id])
                    # old_plots[author_name]['o_dg'].append(o_dg[author_id])
                    # old_plots[author_name]['bn'].append(bn[author_id])
                    old_plots[author_name]['dg'].append(dg[author_id])
                    old_plots[author_name]['pr'].append(pr[author_id])
                    old_plots[author_name]['cn'].append(cn[author_id])

                    # Plot new
                    print("Plotting to chart on year {}".format(year))
                    # ax1.plot(old_plots[author_name]['year'],
                    #          old_plots[author_name]['i_dg'],
                    #          label=author_name,
                    #          color=COLOR_PALETTE[author_idx][0])
                    # ax2.plot(old_plots[author_name]['year'],
                    #          old_plots[author_name]['o_dg'],
                    #          label=author_name,
                    #          color=COLOR_PALETTE[author_idx][1])
                    # ax3.plot(old_plots[author_name]['year'],
                    #          old_plots[author_name]['bn'],
                    #          label=author_name,
                    #          color=COLOR_PALETTE[author_idx][2])
                    ax1.plot(old_plots[author_name]['year'],
                             old_plots[author_name]['dg'],
                             label=author_name,
                             color=COLOR_PALETTE[author_idx][0])
                    ax2.plot(old_plots[author_name]['year'],
                             old_plots[author_name]['pr'],
                             label=author_name,
                             color=COLOR_PALETTE[author_idx][1])
                    ax3.plot(old_plots[author_name]['year'],
                             old_plots[author_name]['cn'],
                             label=author_name,
                             color=COLOR_PALETTE[author_idx][2])

                    # Plot vertical line on year
                    if int(year) >= TURING_AWARD_YEAR:
                        for ax in [ax1, ax2, ax3]:
                            ax.axvline(x=TURING_AWARD_YEAR)

                    # Plot legend in each chart
                    for ax in [ax1, ax2, ax3]:
                        ax.legend()
                    plt.pause(0.001)

    if generate_graph and read_from_dblp:
        print("Finished creating the graph")
        print("Graph size: {} nodes and {} edges".format(
            G.number_of_nodes(), G.number_of_edges()))

    # Turn interactive plot off
    plt.ioff()
    plt.savefig(plot_save_path)
    plt.pause(5)

    # Save graph to .gml
    if save_gml:
        nx.write_gml(G, DATASET_BASE_PATH +
                     '{}_{}'.format(CONFERENCE_NAME, graph_file))
        print("Saved graph to .gml file")

    # Write json data to file
    if save_records:
        with open('./dblp_arnet/{}.json'.format(CONFERENCE_NAME), 'w') as f:
            json.dump(conference_papers, f)
        print("Saved conference json")


if __name__ == "__main__":
    fire.Fire(generate_graph)
